apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
spec:
  project: default
  source:
    path: apps/core
    repoURL: https://github.com/ronsevetoci/argocd.git
    targetRevision: HEAD
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
